if (room == rm_sandbox)
{
	add_game_camera(0, VIEW_DEFAULT_WIDTH, VIEW_DEFAULT_HEIGHT, 0, 0, 1, 0.5, VIEW_DEFAULT_FOLLOW_OBJECT);
	add_game_camera(1, VIEW_DEFAULT_WIDTH, VIEW_DEFAULT_HEIGHT, 0, 0.5, 0.5, 0.5, VIEW_DEFAULT_FOLLOW_OBJECT);
	add_game_camera(2, VIEW_DEFAULT_WIDTH, VIEW_DEFAULT_HEIGHT, 0.5, 0.5, 0.5, 0.5, VIEW_DEFAULT_FOLLOW_OBJECT);	
}
